api/urls.py
from django.urls import path
from .views import ListEventsView, LiveEventsView


urlpatterns = [
    path('events/', ListEventsView.as_view(), name="events-all"),
    path('sports/', LiveEventsView.as_view(), name="live-events"),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('upload_players', views.upload_player, name='upload_players'),
    path('available_lineups', views.available_lineups, name='available_lineups'),
    path('stats', views.stats, name='stats'),
    path('starters_order', views.starters_order, name='starters_order'),
    path('stack_builder', views.stack_builder, name='stack_builder'),
    path('', views.index, name='index'),
    path('pitching', views.pitching_stats, name='pitching'),
    path('stacks', views.stacks_stats, name='stacks'),
    path('pstats', views.team_stats, name='pstats'),
    path('player_bats', views.player_bats, name='player_bats'),
    path('pull_projections', views.pull_projections, name='pull_projections'),
    path('stacks_call', views.stacks_call, name='stacks_call'),
    path('pown', views.player_pown, name='pown'),
    path('add_starter', views.add_starter, name='add_starter'),
]

slate/urls.py
from django.urls import path
from . import views

app_name = 'slate'

urlpatterns = [
    path("stack_add", views.stack_add, name="stack_add"),
    path("remove", views.remove, name="remove"),
    path("lineups", views.lineups, name="lineups"),
    path("add_lineups", views.add_lineups, name="add_lineups"),
    path("delete_all", views.delete_all, name="delete_all"),
    path("update_orders", views.update_pro_orders, name="update_pro_orders"),
    path("lineup_check", views.lineup_check, name="lineup_check"),
    path("refresh_lus", views.refresh_big_kahuna, name="refresh_lus"),
    path("add_punts", views.add_punts, name="add_punts"),
    path("remove_punts", views.remove_punts, name="remove_punts"),
    path("delete_bad_lines", views.delete_bad_lines, name="delete_bad_lines"),
    path("update_line_lineups", views.update_live_lineups, name="update_live_lineups"),
    path("team_breakdown", views.team_breakdown, name="team_breakdown"),
    path("lineup_builder", views.lineup_builder, name="lineup_builder"),
    path("pitcher_combos", views.pitcher_combos, name="pitcher_combos"),
    path("delete_pcombo", views.delete_pcombo, name="delete_pcombo"),
]

thebook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from sportsbook import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^sportsbook/', include('sportsbook.urls', namespace='sportsbook')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^betslip/', include('betslip.urls', namespace='betslip')),
    path('api/', include('api.urls')),
    path("players/", include('players.urls', namespace='players')),
    path("slate/", include('slate.urls', namespace='slate')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

players/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.template.loader import render_to_string

import json

from .models import Player
from .tasks import (orders, starting_pitchers, upload_stats, upload_salaries, upload_batting_hands,
                    pown, update_projected_ownership_full)

from teams.models import Team
from slate.models import Stack, Punt
from slate.utls import (todays_stacks, todays_pitchers, tp_utils, stack_utils, pstats, indy_pitcher)


def index(request):
    return render(request, "players/index.html", {})


def upload_player(request):
    if request.method == "POST":
        dk_csv = request.FILES["file"]
        if not dk_csv.name.endswith('.csv'):
            error = True  # ???????
        upload_salaries(dk_csv)
    cont_dict = {}
    return render(request, "players/upload_players.html", cont_dict)


def available_lineups(request):
    cont_dict = {}
    return render(request, "players/upload_players.html", cont_dict)


def stats(request):
    if request.method == "POST":
        for f in request.FILES:
            player_data = request.FILES[f]
            upload_stats(player_data, f)
    return render(request, "players/stats_upload.html", {})


def starters_order(request):
    orders()
    starting_pitchers()
    return redirect("players:upload_players")


def stack_builder(request):
    players = {}
    user = request.user
    current_team = ""
    if request.method == "POST":
        team = request.POST.get("team")
        players = Player.objects.filter(team=team).exclude(position="SP").exclude(position="RP").order_by('-order_pos')
        current_team = team
    teams = Team.objects.filter(on_slate=True).order_by("dk_name")
    stacks = Stack.objects.filter(user=user)
    punts = Punt.objects.filter(user=user)
    cont_dict = {
        "teams": teams,
        "players": players,
        "stacks": stacks,
        "punts": punts,
        "current_team": current_team,
    }
    return render(request, "players/stack_builder.html", cont_dict)


def pitching_stats(request):
    pitchers = todays_pitchers()
    tp_data = tp_utils()
    no_starter = Player.objects.missing_starter()
    all_teams_pitchers = []
    for r in tp_data:
        r['min'] = float(r['min']) if r['min'] is not None else 0
        r['max'] = float(r['max']) if r['max'] is not None else 0
        r['avg'] = float(r['avg']) if r['avg'] is not None else 0
        r['std'] = float(r['std']) if r['std'] is not None else 0
    if request.method == "POST":
        all_teams_pitchers = Player.objects.filter(team=request.POST.get("team"), position="SP")
    cont_dict = {
        'pitchers': pitchers,
        'cols': json.dumps(tp_data),
        "no_starter": no_starter,
        "all_teams_pitchers": all_teams_pitchers
    }
    return render(request, "players/pitcher_stats.html", cont_dict)


def stacks_stats(request):
    stacks = todays_stacks()
    stacks_utils = stack_utils()
    for r in stacks_utils:
        r['min'] = float(r['min']) if r['min'] is not None else 0
        r['max'] = float(r['max']) if r['max'] is not None else 0
        r['avg'] = float(r['avg']) if r['avg'] is not None else 0
        r['std'] = float(r['std']) if r['std'] is not None else 0
    cont_dict = {
        'stacks': stacks,
        'cols': json.dumps(stacks_utils)
    }
    return render(request, "players/stack_stats.html", cont_dict)


def team_stats(request):
    team = request.POST.get("team")
    pitcher = request.POST.get("pitcher")
    if request.is_ajax:
        pr, pl = indy_pitcher(pitcher)
        cont_dict = {
            'players': pstats(team),
            'pl': pl[0] if len(pl) > 0 else None,
            'pr': pr[0] if len(pr) > 0 else None,
            'current_team': team
        }
        html = render_to_string("players/pstats.html", cont_dict, request=request)
        response_data = {"html": html}
        return JsonResponse(response_data)
    cont_dict = {
        'players': pstats(team)
    }
    return render(request, "players/pstats.html", cont_dict)


def player_bats(request):
    if request.method == "POST":
        dk_csv = request.FILES["file"]
        if not dk_csv.name.endswith('.csv'):
            return redirect("players:stats")
        upload_batting_hands(dk_csv)
    return redirect("players:stats")


def player_pown(request):
    if request.method == "POST":
        dk_csv = request.FILES["file"]
        if not dk_csv.name.endswith('.csv'):
            return redirect("players:stats")
        pown(dk_csv)
    return redirect("players:stats")


def pull_projections(request):
    update_projected_ownership_full()
    return redirect("players:stack_builder")


def stacks_call(request):
    user = request.user
    stack = Stack.objects.filter(user=user)
    punts = Punt.objects.filter(user=user)
    cont_dict = {
        "stacks": stack,
        "punts": punts,
    }
    if request.is_ajax:
        html = render_to_string("players/stack_players.html", cont_dict, request=request)
        response_data = {"html": html}
        return JsonResponse(response_data)
    return render(request, "players/stack_players.html", cont_dict)


def add_starter(request):
    if request.method == "POST":
        pid = int(request.POST.get("player"))
        Player.objects.filter(pk=pid).update(starting=True)
    return redirect("players:pitching")

players/templates/players/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<body class="body">
<div class="main" style="margin: 20px">
    <a href="{% url 'players:upload_players' %}">Upload DK Players</a><br>
    <a href="{% url 'players:stats' %}">Upload Player Stats</a><br>
    <a href="{% url 'players:stack_builder' %}">Build Stacks</a><br>
    <a href="{% url 'players:starters_order' %}">Get Starters and Batting Order</a><br>
    <a href="{% url 'slate:update_pro_orders' %}">Update Projected Orders</a><br>
    <a href="{% url 'slate:update_live_lineups' %}">Update Live Orders</a><br>
    <a href="{% url 'players:pull_projections' %}">Pull Projections</a><br>
</div>
</body>
{% endlocaltime %}
{% endblock %}

players/templates/players/pitcher_stats.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<body class="body">
<div class="main" style="margin: 20px">
    <table id="example" class="display compact order-column stripe row-border" style="width:100%">
        <thead>
            <tr>
                <th>Name</th>
                <th>Team</th>
                <th>H/A</th>
                <th>Throws</th>
                <th>Sal</th>
                <th>Ave</th>
                <th>ERA</th>
                <th>WHIP</th>
                <th>Kp 9</th>
                <th>HRp 9</th>
                <th>K%</th>
                <th>OPP</th>
                <th>OPP K%</th>
                <th>OPP ISO</th>
                <th>OPP wOBA</th>
                <th>Park Runs</th>
                <th>Park HR</th>
                <th>Pfx</th>
                <th>SwStr%</th>
                <th>Soft</th>
                <th>Hard</th>
                <th>FB</th>
                <th>GB</th>
            </tr>
        </thead>
        <tbody>
        {% if pitchers %}
        {% for p in pitchers %}
            <tr>
                <td>{{ p.dk_name }}</td>
                <td>{{ p.Team }}</td>
                <td>{{ p.Home }}</td>
                <td>{{ p.throws }}</td>
                <td>{{ p.salary }}</td>
                <td>{{ p.avg }}</td>
                <td>{{ p.era }}</td>
                <td>{{ p.whip }}</td>
                <td>{{ p.kk_p9 }}</td>
                <td>{{ p.hr_p9 }}</td>
                <td>{{ p.kp }}</td>
                <td>
                    <a href="#" data-toggle="modal" class="team-stats"  data-team="{{ p.opp }}" data-pitcher="{{ p.dk_name }}">{{ p.opp }}</a>
                </td>
                <td>{{ p.OPP_K }}</td>
                <td>{{ p.OPP_ISO }}</td>
                <td>{{ p.OPP_wOBA }}</td>
                <td>{{ p.park_runs }}</td>
                <td>{{ p.park_hr }}</td>
                <td>{{ p.Pfx }}</td>
                <td>{{ p.swstr }}</td>
                <td>{{ p.soft }}</td>
                <td>{{ p.hard }}</td>
                <td>{{ p.fb }}</td>
                <td>{{ p.gb }}</td>
            </tr>
        {% endfor %}
        {% endif %}
        </tbody>
        <tfoot>
            <tr>
                <th>Name</th>
                <th>Team</th>
                <th>H/A</th>
                <th>Throws</th>
                <th>Sal</th>
                <th>Ave</th>
                <th>ERA</th>
                <th>WHIP</th>
                <th>Kp 9</th>
                <th>HRp 9</th>
                <th>K%</th>
                <th>OPP</th>
                <th>OPP K%</th>
                <th>OPP ISO</th>
                <th>OPP wOBA</th>
                <th>Park Runs</th>
                <th>Park HR</th>
                <th>Pfx</th>
                <th>SwStr%</th>
                <th>Soft</th>
                <th>Hard</th>
                <th>FB</th>
                <th>GB</th>
            </tr>
        </tfoot>
    </table>
    {% if no_starter %}
    <div class="row">
          <form action="{% url 'players:pitching' %}" method="POST">{% csrf_token %}
            <select name="team">
                {% for t in no_starter %}
                <option value="{{ t }}">{{ t }}</option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-primary btn-sm">Get Pitchers</button>
        </form>
    </div>
    <div class="row">
        <form action="{% url 'players:add_starter' %}" method="POST">{% csrf_token %}
            {% if all_teams_pitchers %}
            {% for p in all_teams_pitchers %}
            <input style="padding; 3px" type="checkbox" name="player" value="{{ p.pk }}">
            {{ p }}<br>
            {% endfor %}
            {% endif %}
            <input type="submit" class="btn btn-primary btn-sm">
        </form>
    </div>
    {% endif %}
    <div class="modal fade bd-example-modal-lg" id="bannerformmodal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-lg" style="width:1500px">
        <div class="modal-content" id="pstats-modal" style="width:1000px">
        </div>
      </div>
    </div>
</div>
</body>

<script type="text/javascript" charset="utf8">
    $(document).ready(function() {
        $('#example').dataTable( {
            paging: false
        } );

        function opacityGetter(avg, std, low, val) {
            var diff = val - avg
            var opac = Math.abs((diff / std) / 2.5)
            if ( opac > 1 ) {
                opac = 1;
            };
            if ( diff > 0 && low ) {
                var color = 'rgba(255,0,0,' + opac + ')'
            } else if ( diff <= 0 && low ) {
                var color = 'rgba(0,255,0,' + opac + ')'
            } else if ( diff > 0 && !low ) {
                var color = 'rgba(0,255,0,' + opac + ')'
            } else {
                var color = 'rgba(255,0,0,' + opac + ')'
            }
            return color;
        };

        var cols = {{ cols|safe }};

        for (var i = 0; i < cols.length; i++) {
            var avg = cols[i].avg;
            var std = cols[i].std;
            var col = cols[i].numb;
            var low = cols[i].low;

            $('table td:nth-child(' + col + ')').each(function() {
                var val = $(this).text();
                var color = opacityGetter(avg, std, low, val)
                $(this).css('backgroundColor', color);
            });

        }

        $('.team-stats').click(function() {
            var team = $(this).attr('data-team')
            var pitcher = $(this).attr('data-pitcher')
            var url = '{% url 'players:pstats' %}';
            var method = 'POST'
            var data = {"team": team, "pitcher": pitcher}
            $.ajax({
                url: url,
                method: method,
                data: data,
                success: function(responseData){
                    $( "#pstats-modal" ).html(responseData.html);
                    $('#pstats').dataTable( {
                        paging: false
                    } );
                    $('#indy-pitcher').dataTable( {
                        paging: false
                    } );
                    $('#bannerformmodal').modal('show');
                }, error: function(error){
                    console.log(error);
                }
            })
        });

    } );
</script>
{% endlocaltime %}
{% endblock %}

players/templates/players/pstats.html
<form action="{% url 'slate:stack_add' %}" method="POST" id="stack-builder">{% csrf_token %}
    {% if current_team %}
    <input type="hidden" name="team" value="{{ current_team }}"><br>
    {% endif %}
    <table id="indy-pitcher" class="display compact order-column stripe row-border">
        <thead>
            <tr>
                <th>Name</th>
                <th>VS</th>
                <th>ERA</th>
                <th>AVG</th>
                <th>WHIP</th>
                <th>BB/9</th>
                <th>KK/9</th>
                <th>HR/9</th>
                <th>K%</th>
            </tr>
        </thead>
        <tbody>
        {% if pr %}
            <tr>
                <td>{{ pr.dk_name }}</td>
                <td>R</td>
                <td>{{ pr.era }}</td>
                <td>{{ pr.avg }}</td>
                <td>{{ pr.whip }}</td>
                <td>{{ pr.bb_p9 }}</td>
                <td>{{ pr.kk_p9 }}</td>
                <td>{{ pr.hr_p9 }}</td>
                <td>{{ pr.kp }}</td>
            </tr>
        {% endif %}
        {% if pl %}
            <tr>
                <td>{{ pl.dk_name }}</td>
                <td>L</td>
                <td>{{ pl.era }}</td>
                <td>{{ pl.avg }}</td>
                <td>{{ pl.whip }}</td>
                <td>{{ pl.bb_p9 }}</td>
                <td>{{ pl.kk_p9 }}</td>
                <td>{{ pl.hr_p9 }}</td>
                <td>{{ pl.kp }}</td>
            </tr>
        {% endif %}
        </tbody>
        <tfoot>
            <tr>
                <th>Name</th>
                <th>VS</th>
                <th>ERA</th>
                <th>AVG</th>
                <th>WHIP</th>
                <th>BB/9</th>
                <th>KK/9</th>
                <th>HR/9</th>
                <th>K%</th>
            </tr>
        </tfoot>
    </table>
    <table id="pstats" class="display compact order-column stripe row-border">
        <thead>
            <tr>
                <th>Name</th>
                <th>Salary</th>
                <th>POS</th>
                <th>Pos2</th>
                <th>Order</th>
                <th>AVG</th>
                <th>SLG</th>
                <th>OPS</th>
                <th>ISO</th>
                <th>wOBA</th>
                <th>HARD%</th>
                <th>wOBAd</th>
                <th>ISOd</th>
                <th>K%</th>
                <th>PAs</th>
                <th>PROJ</th>
                <th>POWN</th>
                <th>Add</th>
            </tr>
        </thead>
        <tbody>
        {% if players %}
        {% for p in players %}
            <tr>
                <td>{{ p.dk_name }} ({{ p.bats }})</td>
                <td>{{ p.salary }}</td>
                <td>{{ p.position }}</td>
                <td>{{ p.second_pos }}</td>
                <td>{{ p.order_pos }}</td>
                <td>{{ p.avg }}</td>
                <td>{{ p.slg }}</td>
                <td>{{ p.ops }}</td>
                <td>{{ p.iso }}</td>
                <td>{{ p.woba }}</td>
                <td>{{ p.hard_p }}</td>
                <td>{{ p.wobaDiff }}</td>
                <td>{{ p.isoDiff }}</td>
                <td>{{ p.kp }}</td>
                <td>{{ p.pa }}</td>
                <td>{{ p.pts }}</td>
                <td>{{ p.proj_pown }}</td>
                <td><input style="padding; 3px" type="checkbox" name="{{ p.id }}" value="player"></td>
            </tr>
        {% endfor %}
        {% endif %}
        </tbody>
        <tfoot>
            <tr>
                <th>Name</th>
                <th>Salary</th>
                <th>POS</th>
                <th>Pos2</th>
                <th>Order</th>
                <th>AVG</th>
                <th>SLG</th>
                <th>OPS</th>
                <th>ISO</th>
                <th>wOBA</th>
                <th>HARD%</th>
                <th>wOBAd</th>
                <th>ISOd</th>
                <th>K%</th>
                <th>PAs</th>
                <th>PROJ</th>
                <th>POWN</th>
                <th>Add</th>
            </tr>
        </tfoot>
    </table>
    <button type="submit" class="btn btn-primary" id="submit-stack">Add Players</button>
    <input type="submit" class="btn btn-primary" value="Add Punts" id="punt-submit">
</form>
<script type="text/javascript" charset="utf8">
    $(document).ready(function () {
        $('#stack-builder').submit(function (e) {
            e.preventDefault();
            var url = "{% url 'slate:stack_add' %}";
            var method = 'POST';
            var data = $(this).serializeArray();
            $.ajax({
                url: url,
                method: method,
                data: data,
                success: function (responseData) {
                    $("#stacks-modal").html(responseData.html);
                    $('#bannerformmodal').modal('hide');
                    $('#stack-modal-banner').modal('show');
                }, error: function (error) {
                    console.log(error);
                }
            })
        });

        $('#punt-submit').click(function () {
            var url = "{% url 'slate:add_punts' %}";
            var method = 'POST';
            var data = $('#stack-builder').serializeArray();
            $.ajax({
                url: url,
                method: method,
                data: data,
                success: function (responseData) {
                    $("#stacks-modal").html(responseData.html);
                    $('#bannerformmodal').modal('hide');
                    $('#stack-modal-banner').modal('show');
                }, error: function (error) {
                    console.log(error);
                }
            })
        });

    });
</script>

players/templates/players/stack_builder.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<body class="body">
<div class="main" style="font-size: 2em">
    <div style="float: left">
        <form action="{% url 'players:stack_builder' %}" method="POST">{% csrf_token %}
            <select name="team">
                {% if teams %}
                {% for t in teams %}
                <option value="{{ t }}">{{ t }}</option>
                {% endfor %}
                {% endif %}
            </select>
            <button type="submit" class="btn btn-primary">Get Players</button>
        </form>
        <form action="{% url 'slate:stack_add' %}" method="POST">{% csrf_token %}
            {% if current_team %}
            <h1>{{ current_team }}</h1>
            <input type="hidden" name="team" value="{{ current_team }}"><br>
            {% endif %}
            {% if players %}
            {% for p in players %}
            <input style="padding; 3px" type="checkbox" name="{{ p.pk }}" value="player">
            {{ p.dk_name }} {{ p.position }} {{ p.second_pos }} {{ p.salary }} Order: {{ p.order_pos }} Calc POwn: {{ p.proj_pown }}<br>
            {% endfor %}
            {% endif %}
            <button type="submit" class="btn btn-primary">Add Players</button>
            <input type="submit" class="btn btn-primary" value="Add Punts" formaction="{% url 'slate:add_punts' %}">
        </form>
        <form action="{% url 'slate:refresh_lus' %}">
            <button type="submit">Refresh Big Kahuna</button>
        </form>
    </div>
    {% include 'players/stack_players.html' %}
</div>
</body>
{% endlocaltime %}
{% endblock %}

players/templates/players/stack_players.html
<div style="float: right">
    <form action="{% url 'slate:remove' %}" method="POST" id="stacks-remove">{% csrf_token %}
        {% if stacks %}
        {% for s in stacks %}
        <h1>{{ s.team }}</h1>
        {% for p in s.players.all %}
        <input type="checkbox" name="{{ p.pk }}" value="player">{{ p }}<br>
        {% endfor %}
        {% endfor %}
        {% endif %}
        <button type="submit" class="btn btn-primary">Remove Players</button>
    </form>
</div>
<div style="float: right">
    <form action="{% url 'slate:remove_punts' %}" method="POST" id="punts-remove">{% csrf_token %}
        {% if punts %}
        {% for p in punts %}
        <input type="checkbox" name="{{ p.pk }}" value="player">{{ p }}<br>
        {% endfor %}
        {% endif %}
        <button type="submit" class="btn btn-primary">Remove punt</button>
    </form>
</div>
<script type="text/javascript" charset="utf8">
    $(document).ready(function () {
        $('#punts-remove').submit(function (e) {
            e.preventDefault();
            var url = "{% url 'slate:remove_punts' %}";
            var method = 'POST';
            var data = $(this).serializeArray();
            console.log(data);
            $.ajax({
                url: url,
                method: method,
                data: data,
                success: function (responseData) {
                    $("#stacks-modal").html(responseData.html);
                    $('#bannerformmodal').modal('hide');
                    $('#stack-modal-banner').modal('show');
                }, error: function (error) {
                    console.log(error);
                }
            })
        });

        $('#stacks-remove').submit(function (e) {
            e.preventDefault();
            var url = "{% url 'slate:remove' %}";
            var method = 'POST';
            var data = $(this).serializeArray();
            console.log(data);
            $.ajax({
                url: url,
                method: method,
                data: data,
                success: function (responseData) {
                    $("#stacks-modal").html(responseData.html);
                    $('#bannerformmodal').modal('hide');
                    $('#stack-modal-banner').modal('show');
                }, error: function (error) {
                    console.log(error);
                }
            })
        });

    });
</script>

players/templates/players/stats_upload.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<body class="body">
<div class="main">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label>Batting ALL</label>
        <input type="file" name="ball">
        <label>Batting vs Right</label>
        <input type="file" name="br">
        <label>Batting vs Left</label>
        <input type="file" name="bl">
        <label>Batting Streak</label>
        <input type="file" name="bs">
        <label>Pitching ALL</label>
        <input type="file" name="pall">
        <label>Pitching vs Right</label>
        <input type="file" name="pr">
        <label>Pitching vs Left</label>
        <input type="file" name="pl">
        <label>Pitching Streak</label>
        <input type="file" name="ps">
        <label>Team Batting vs Right</label>
        <input type="file" name="tr">
        <label>Team Batting vs Left</label>
        <input type="file" name="tl">
        <button type="submit" class="btn btn-secondary">Upload All</button>
    </form>
    <form method="post" enctype="multipart/form-data" action="{% url 'players:player_bats' %}">
        {% csrf_token %}
        <label>Upload a file</label>
        <input type="file" name="file">
        <button type="submit" class="btn btn-secondary">Batting Hands</button>
    </form>
    <form method="post" enctype="multipart/form-data" action="{% url 'players:pown' %}">
        {% csrf_token %}
        <label>Upload a file</label>
        <input type="file" name="file">
        <button type="submit" class="btn btn-secondary">P Ownership</button>
    </form>
</div>
</body>
{% endlocaltime %}
{% endblock %}

players/templates/players/upload_players.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<body class="body">
<div class="main">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label>Upload a file</label>
        <input type="file" name="file">
        <button type="submit" class="btn btn-secondary">Upload Players</button>
    </form>
    <a href="{% url 'players:starters_order' %}">STARTERS and Batting Order</a>
</div>
</body>
{% endlocaltime %}
{% endblock %}