api/urls.py
from django.urls import path
from .views import ListEventsView, LiveEventsView


urlpatterns = [
    path('events/', ListEventsView.as_view(), name="events-all"),
    path('sports/', LiveEventsView.as_view(), name="live-events"),
]

betslip/urls.py
from django.conf.urls import url
from .views import slip_home, slip_update, parley_update, submit_bet, check_out, cancel_bet


app_name = 'betslip'

urlpatterns = [
    url(r'^$', slip_home, name='home'),
    url(r'^update/$', slip_update, name='update'),
    url(r'^parley_update/$', parley_update, name='parley_update'),
    url(r'^submit_bet/$', submit_bet, name='submit_bet'),
    url(r'^check_out/$', check_out, name='check_out'),
    url(r'^cancel_bet/$', cancel_bet, name='cancel_bet'),
]

thebook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from sportsbook import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^sportsbook/', include('sportsbook.urls', namespace='sportsbook')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^betslip/', include('betslip.urls', namespace='betslip')),
    path('api/', include('api.urls')),
    path("players/", include('players.urls', namespace='players')),
    path("slate/", include('slate.urls', namespace='slate')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

betslip/models.py
from django.db import models
from django.db.models import Sum
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save, m2m_changed
from decimal import Decimal
from django.utils import timezone
from django.contrib import admin
from django.db.models import Q
import uuid
from sportsbook.models import Odds, Event, OddsGroup
from account.models import Account
from datetime import datetime, timedelta


class BetSlipManager(models.Manager):
    # Used to get users betslip throught the website
    # is this the same as get_or_create???
    def new_or_get(self, request):
        slip_id = request.session.get('slip_id', None)
        qs = self.get_queryset().filter(id=slip_id)
        if qs.count() == 1:
            new_obj = False
            slip_obj = qs.first()
            if request.user.is_authenticated and slip_obj.user is None:
                slip_obj.user = request.user
                slip_obj.save()
        else:
            slip_obj = Slip.objects.new(user=request.user)
            new_obj = True
            request.session['slip_id'] = slip_obj.id
        return slip_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


# Slip used to hold the bets and and products for user
# Functions like a cart but with bets
class Slip(models.Model):
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    odds = models.ManyToManyField(Odds, blank=True)
    divider = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    updated = models.DateTimeField(auto_now=True)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    due = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = BetSlipManager()

    def __str__(self):
        return str(self.pk)

    # if odds_obj is in cart already, delete else add
    def add_or_remove_odd(self, odds_obj):
        if odds_obj in self.odds.all():
            self.odds.remove(odds_obj)
            added = False
        else:
            self.odds.add(odds_obj)
            added = True
        return added

    # Check to see if the games have started already
    def get_earliest_start_time(self):
        start = timezone.now() + timezone.timedelta(days=365)
        for odd in self.odds.all():
            s = odd.get_event_start_time()
            if s < start:
                start = s
        return start

    def remove_nonpregame_odds(self):
        for odd in self.odds.all():
            if odd.get_event_start_time() < timezone.now():
                self.odds.remove(odd)
        return

    # Creates a PlacedBet and BetValue for all odds in the slip
    def create_straight_bets(self, post):
        total_collected = 0
        for bet in self.odds.all():
            collected = Decimal(post['risk-{}'.format(bet.pk)])
            if collected != 0:
                value = Decimal(collected * bet.get_multiplier())
                new_placed = PlacedBet.objects.create(
                    user=self.user,
                    value=value,
                    divider=self.divider,
                    collected=collected,
                    sum_odds=bet.get_multiplier(),
                    placed=timezone.now(),
                    type="S",
                    start_time=bet.get_event_start_time()
                )
                odd_group = bet.get_odd_group()
                BetValue.objects.create(
                    placed_bet=new_placed,
                    odd=bet,
                    value=value,
                    placed_price=bet.price,
                    type=bet.type,
                    event=odd_group.event,
                    total=odd_group.total,
                    handicap=odd_group.handicap,
                    odd_group=odd_group
                )
                total_collected += collected
        return total_collected

    # Creates Placed with all odds as the parlay values
    def create_parlay(self, post):
        risk_amount = post['parlay-risk-input']
        total = 0
        if risk_amount:
            total = Decimal(risk_amount)
            win = Decimal(total * self.divider)
            new_placed = PlacedBet.objects.create(
                user=self.user,
                value=win,
                divider=self.divider,
                collected=total,
                placed=timezone.now(),
                type="P",
                start_time=self.get_earliest_start_time()
            )
            for bet in self.odds.all():
                bet_value = Decimal(win / (self.divider / bet.get_multiplier()))
                odd_group = bet.get_odd_group()
                BetValue.objects.create(
                    placed_bet=new_placed,
                    odd=bet,
                    value=bet_value,
                    placed_price=bet.price,
                    type=bet.type,
                    event=odd_group.event,
                    total=odd_group.total,
                    handicap=odd_group.handicap,
                    odd_group=odd_group
                )
        return total


# Change receiver for adding odds to betslip
def m2m_changed_slip_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        odds = instance.odds.all()
        divide = 1
        for x in odds:
            mult = x.get_multiplier()
            divide = divide * mult
        if instance.divider != divide:
            instance.divider = divide
            instance.save()


m2m_changed.connect(m2m_changed_slip_receiver, sender=Slip.odds.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.divider > 0 and instance.total > 0:
        instance.due = Decimal(instance.total) / Decimal(instance.divider)
    else:
        instance.due = 0


pre_save.connect(pre_save_cart_receiver, sender=Slip)


class PlacedBetpManager(models.Manager):
    def update_all_bet_values(self):  # does this go here?
        bets = self.get_queryset().all()
        for bet in bets:
            bet.update_bet_values()

    def active(self):
        return self.get_queryset().filter(status=0)

    def total_handle(self):
        return self.active().aggregate(Sum("collected"))

    def total_risk(self):  # Need Raw Sql to get actual risk
        return self.active().aggregate(Sum("value"))

    def bet_histry(self, user, request=None):
        all_settled = self.get_queryset().filter(user=user).exclude(status=0)
        if request is not None:
            start = request.POST.get("history-start-date").split("-")
            start_dt = datetime(int(start[0]), int(start[1]), int(start[2]))
            end = request.POST.get("history-end-date").split("-")
            end_dt = datetime(int(end[0]), int(end[1]), int(end[2]))
            all_settled = all_settled.filter(start_time__range=(start_dt, end_dt))
        return all_settled


# All placed bets
class PlacedBet(models.Model):
    STATUS_OPTIONS = (
        (0, 'active'),
        (1, 'lose'),
        (2, 'win'),
        (3, 'push')
    )
    TYPE_CHOICES = (
        ("S", "striaght"),
        ("P", "parlay")
    )
    placed_id = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    odds = models.ManyToManyField(Odds, through="BetValue")
    divider = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    sum_odds = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    placed = models.DateTimeField()
    collected = models.DecimalField(default=0.00, max_digits=10, decimal_places=2)
    value = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    start_time = models.DateTimeField(null=True)
    status = models.IntegerField(choices=STATUS_OPTIONS, default=0)
    type = models.CharField(max_length=24)

    objects = PlacedBetpManager()

    def __str__(self):
        return "{}: Value: {}".format(self.user, self.value)

    def update_bet_values(self):
        bets = self.betvalue_set.all()
        if bets:
            price_sum = 0
            for bet in bets:
                if bet.status == 0:
                    price_sum += bet.get_multiplier()
                elif bet.status == 2:
                    bet.value = 0
                    bet.save()
            if price_sum != 0:
                for bet in bets:
                    if bet.status == 0:
                        bet.value = Decimal(self.value / (price_sum / bet.get_multiplier()))
                    bet.save()
        return

    def update_straight(self):
        if self.status == 0:
            bet = self.betvalue_set.all().first()
            self.status = bet.status
            if self.status == 2 or self.status == 3:
                self.pay_winners_or_push()
            self.save()
        return

    def update_parlay(self):
        if self.status == 0:
            bets = self.betvalue_set.all()
            if bets.filter(status=1).exists():  # if there is losing bet
                bets.update(value=0)
                self.status = 1
                print("{} is a loser".format(self))
            elif bets.filter(status=3).exists():  # If there is bet that isn't final yet
                value = self.updated_value_from_push()
                self.value = value
            if bets.filter(Q(status=2) | Q(status=3)).count() == bets.count():  # All bets will be winners at this point
                print("{} is a winner!!".format(self))
                self.status = 2
                self.pay_winners_or_push()
            self.save()
        return

    def updated_value_from_push(self):
        bets = self.betvalue_set.filter(~Q(status=3))
        multiplier = 1

betslip/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from .models import *
from decimal import Decimal
from sportsbook.models import Odds
from django.core.serializers import serialize
from account.models import Account
from .utls import validate_slip
from django.db import transaction
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

import json


def slip_home(request):
    slip_obj, new_obj = Slip.objects.new_or_get(request)
    if slip_obj.divider == 0 or slip_obj.odds.count() == 5:
        min_price = -10000
    else:
        cnt = Decimal(1 / int(5 - slip_obj.odds.count()))
        max_divider = (20 / slip_obj.divider) ** (cnt)
        if max_divider < 2:
            min_price = -100 / (max_divider - 1)
        else:
            min_price = (max_divider - 1) * 100
    odds_list = Odds.objects.filter(price__gte=min_price)
    cont_dict = {
        'slip': slip_obj,
        'odds': odds_list,
    }
    return render(request, 'betslip/home.html', context=cont_dict)


# Update BetSkip with odd or product
# Used in ajax calls in shop/sportsbook templates
def slip_update(request):
    odds_id = request.POST.get('bet_id')
    added = False
    # If odds_id exists, get odd, then get slip and add odd to slip
    if odds_id:
        try:
            odds_obj = Odds.objects.get(odd_id=odds_id)
        except Odds.DoesNotExist:
            print('Odds does not exist')
            return redirect('sportsbook:home')
        slip_obj, new_obj = Slip.objects.new_or_get(request)
        added = slip_obj.add_or_remove_odd(odds_obj)
        request.session['slip_odds'] = str(round(slip_obj.divider, 2))
        request.session['slip_due'] = str(round(slip_obj.due, 2))
    # Serialize bet and send back with ajax - Old
    # render sidebar template and return it as a string - new
    if request.is_ajax:
        numb_bets = slip_obj.odds.all().count()
        slip_dict = {"slip": slip_obj}
        html = render_to_string("sportsbook/sidebar.html", slip_dict, request=request)
        response_data = {"html": html, 'bets': numb_bets}
        return JsonResponse(response_data)
    return redirect('betslip:home')


# Update a parlay with either a bet
# used in betslip_home
def parley_update(request):
    # Get bet_id, if exists, get odd
    odds_id = request.POST.get('bet_id')
    if odds_id is not None:
        try:
            odds_obj = Odds.objects.get(odd_id=odds_id)
        except Odds.DoesNotExist:
            print('Odds does not exist')
            return redirect('betslip:home')
        slip_obj, new_obj = Slip.objects.new_or_get(request)
        added = slip_obj.add_or_remove_odd(odds_obj)
        request.session['slip_odds'] = str(round(slip_obj.divider, 2))
        request.session['slip_due'] = str(round(slip_obj.due, 2))
        if request.is_ajax:
            min_price = slip_obj.calc_min_price()
            odds_list = serialize('json', Odds.objects.filter(price__gte=min_price, status=0))
            bets = serialize('json', slip_obj.odds.all())
            json_data = {
                "added": added,
                "removed": not added,
                "slipOdds": str(round(slip_obj.divider, 2)),
                "slipDue": str(round(slip_obj.due, 2)),
                "minPrice": min_price,
                "slipBets": bets,
                "oddsRemain": odds_list,
            }
            return JsonResponse(json_data)
    return redirect('betslip:home')


# Submits all bets
@login_required(login_url="/")
def submit_bet(request):
    if not request.user.is_authenticated:
        return redirect('account:signup')
    try:
        slip_obj, new_obj = Slip.objects.new_or_get(request)
    except Slip.DoesNotExist:
        print('Slip does not exist')
        return redirect('betslip:home')
    if request.method == 'POST':
        post = request.POST
        try:
            account = Account.objects.get(user=request.user)
        except Account.DoesNotExist:
            return redirect('account:signup')  # Change to Sign In
        # Check if bet slip is valid
        #   1. Check game start times
        #   2. Check account balance
        #   3. Check account limits
        valid, message = validate_slip(slip_obj, account, post)  # Returns Bool for valid and error Message
        if valid:
            due = 0
            # Create PlacedBets and BetValues
            if "parlay-checkbox" in post:
                due += slip_obj.create_parlay(post)
            due += slip_obj.create_straight_bets(request.POST)
            slip_obj.odds.clear()
            # Get account for update and withdraw the total of all the bet.
            with transaction.atomic():
                account_for_withdraw = Account.objects.select_for_update().get(user=request.user)
                account_for_withdraw.balance -= due
                account_for_withdraw.save()
        if request.is_ajax:
            json_data = {
                "valid": valid,
                "errorMessage": message,
            }
            return JsonResponse(json_data)
    return redirect('account:active_bets')


def check_out(request):
    if not request.user.is_authenticated:
        return redirect('sportsbook:mlb')
    slip_obj, new_obj = Slip.objects.new_or_get(request)
    cont_dict = {
        'slip': slip_obj,
    }
    return render(request, 'betslip/check_out.html', cont_dict)


@login_required(login_url="/")
def cancel_bet(request):
    '''Cancel bet and refund amount collected. Send with success message?'''
    placed_id = request.POST.get('placed_id')
    try:
        placed_bet = PlacedBet.objects.get(placed_id=placed_id)
    except PlacedBet.DoesNotExist:
        return redirect('account:active_bets')
    refunded = placed_bet.cancel_and_refund()
    if not refunded:
        print("There was an error refunding your account") #Error message??
    return redirect('account:active_bets')

betslip/templates/betslip/check_out.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div classe="row">
            <h1>Parlay</h1>
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Bet</th>
                    <th>Price</th>
                </tr>
                </thead>

                <tbody id="slip-table-body">
                {% for odd in slip.odds.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href='#'>{{ odd.home }}: {{ odd.type }}</a>

                    </td>
                    <td>{{ odd.price }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="2"></td>
                    <td><b>Subtotal</b> {{ slip.divider }}</td>
                </tr>
                </tbody>
            </table>
        </div>
            <div class="row">
            <h1>Bet Slip</h1>
            {% if slip.odds.exists %}
            <table class="table">

                <thead>
                <tr>
                    <th>#</th>
                    <th>Product Name</th>
                    <th>Product Price</th>
                </tr>
                </thead>
                <tbody>
                {% for product in slip.products.all %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href='#'>{{ product.title }}</a>

                    </td>
                    <td>{{ product.price }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="2"></td>
                    <td><b>Total:</b> ${{ slip.total }}</td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                    <td><b>Total Odds</b> {{ slip.divider }}</td>
                </tr>
                <tr>
                    <td colspan="2"></td>
                    <td><b>Due:</b> ${{ slip.due }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        </div>
        {% if not slip.shipping_address %}
        <div class="col-3">
            {% include 'account/snippets/saved_addresses.html' with address_qs=addresses %}
        </div>
        <div class="col-3">
            {% include 'account/snippets/address_form.html' with form=address_form address_type='Billing Address'%}
        </div>
        {% else %}
            <div class="col-3">
                <h1>
                    {{ slip.shipping_address.get_address }}
                </h1>
            </div>
        {% endif %}
    </div>
    {% if slip.shipping_address %}
    <form class="submit-betslip" method="POST" action="{% url 'betslip:submit_bet' %}">{% csrf_token %}
        <div class="row">
            <div class="col-12">
                <button class="btn btn-outline-success bet-button">Submit Bet</button>
            </div>
        </div>
    </form>
    {% endif %}
</div>
{% else %}
<h2>Cart is empty</h2>
{% endif %}

{% endblock %}

betslip/templates/betslip/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
<div class="container">
    <div class="row">
    <div class="col">
        <h1>Bet Slip</h1>
        {% if slip.odds.exists %}
        <table class="table">

            <thead>
            <tr>
                <th>#</th>
                <th>Product Name</th>
                <th>Product Price</th>
            </tr>
            </thead>
            <tbody>
            {% for product in slip.products.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href='#'>{{ product.title }}</a>

                </td>
                <td>{{ product.price }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td><b>Subtotal</b> {{ slip.divider }}</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><b>Total</b> {{ slip.total }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="col">
        <h1>Choose your 5 team Parley!</h1>
        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>Product Name</th>
                <th>Product Price</th>
            </tr>
            </thead>

            <tbody id="slip-table-body">
            {% for odd in slip.odds.all %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href='#'>{{ odd.home }}: {{ odd.type }}</a>

                </td>
                <td>{{ odd.price }}</td>
            </tr>
            {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td><b>Subtotal</b> {{ slip.divider }}</td>
            </tr>
            <tr>
                <td colspan="2"></td>
                <td><b>Total</b> {{ slip.total }}</td>
            </tr>
            </tbody>
        </table>

        <div class="form-group">
            <form class="form-parley-ajax" method="POST" action="{% url 'betslip:parley_update' %}">{% csrf_token %}
                <label for="bet_id">Select list:</label>
                <select class="form-control" id="bet_id" name="bet_id">
                    {% for odd in odds %}
                    <option value="{{ odd.odd_id }}">{{ odd }}  {{ odd.price }}</option>
                    {% endfor %}
                </select>
                <button type="submit" class="btn btn-outline-success bet-button">Add Game</button>
            </form>
        </div>
        <div class="form-group">
            <form class="form-test" method="POST" action="{% url 'betslip:submit_bet' %}">{% csrf_token %}
                <button type="submit" class="btn btn-outline-success bet-button">Submit Bet</button>
            </form>
        </div>
    </div>
    </div>
</div>
{% else %}
<h2>Cart is empty</h2>
{% endif %}

{% endblock %}