api/urls.py
from django.urls import path
from .views import ListEventsView, LiveEventsView


urlpatterns = [
    path('events/', ListEventsView.as_view(), name="events-all"),
    path('sports/', LiveEventsView.as_view(), name="live-events"),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('upload_players', views.upload_player, name='upload_players'),
    path('available_lineups', views.available_lineups, name='available_lineups'),
    path('stats', views.stats, name='stats'),
    path('starters_order', views.starters_order, name='starters_order'),
    path('stack_builder', views.stack_builder, name='stack_builder'),
    path('', views.index, name='index'),
    path('pitching', views.pitching_stats, name='pitching'),
    path('stacks', views.stacks_stats, name='stacks'),
    path('pstats', views.team_stats, name='pstats'),
    path('player_bats', views.player_bats, name='player_bats'),
    path('pull_projections', views.pull_projections, name='pull_projections'),
    path('stacks_call', views.stacks_call, name='stacks_call'),
    path('pown', views.player_pown, name='pown'),
    path('add_starter', views.add_starter, name='add_starter'),
]

slate/urls.py
from django.urls import path
from . import views

app_name = 'slate'

urlpatterns = [
    path("stack_add", views.stack_add, name="stack_add"),
    path("remove", views.remove, name="remove"),
    path("lineups", views.lineups, name="lineups"),
    path("add_lineups", views.add_lineups, name="add_lineups"),
    path("delete_all", views.delete_all, name="delete_all"),
    path("update_orders", views.update_pro_orders, name="update_pro_orders"),
    path("lineup_check", views.lineup_check, name="lineup_check"),
    path("refresh_lus", views.refresh_big_kahuna, name="refresh_lus"),
    path("add_punts", views.add_punts, name="add_punts"),
    path("remove_punts", views.remove_punts, name="remove_punts"),
    path("delete_bad_lines", views.delete_bad_lines, name="delete_bad_lines"),
    path("update_line_lineups", views.update_live_lineups, name="update_live_lineups"),
    path("team_breakdown", views.team_breakdown, name="team_breakdown"),
    path("lineup_builder", views.lineup_builder, name="lineup_builder"),
    path("pitcher_combos", views.pitcher_combos, name="pitcher_combos"),
    path("delete_pcombo", views.delete_pcombo, name="delete_pcombo"),
]

thebook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from sportsbook import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^sportsbook/', include('sportsbook.urls', namespace='sportsbook')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^betslip/', include('betslip.urls', namespace='betslip')),
    path('api/', include('api.urls')),
    path("players/", include('players.urls', namespace='players')),
    path("slate/", include('slate.urls', namespace='slate')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

slate/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.template.loader import render_to_string

from .models import StackPlayer, ExportLineup, Punt, PitcherCombo
from .utls import *
from .tasks import save_lus, refresh_bkg, save_lineups_new_pitchers_first

from teams.models import Team
from teams.tasks import update_projected, manual_live_lu_update
from players.models import Player

pos_swap = {
    "C": "c",
    "1B": "fB",
    "2B": "sB",
    "3B": "tB",
    "SS": "ss",
}


def get_stack_html(r):
    user = r.user
    stack = Stack.objects.filter(user=user)
    punts = Punt.objects.filter(user=user)
    cont_dict = {
        "stacks": stack,
        "punts": punts,
    }
    html = render_to_string("players/stack_players.html", cont_dict, request=r)
    return {"html": html}


# Create your views here.

@login_required(login_url="/")
def stack_add(request):
    if request.method == "POST":
        user = request.user
        team_id = request.POST.get("team")
        team = Team.objects.get(dk_name=team_id)
        stack, created = Stack.objects.get_or_create(user=user, team=team)
        i = 1 if not stack.players.all().exists() else stack.players.all().count() + 1
        for p_id, key in request.POST.items():
            if key == "player":
                p = Player.objects.get(id=int(p_id))
                if not StackPlayer.objects.filter(stack=stack, player=p).exists():
                    sp = StackPlayer(stack=stack, player=p, order_spot=i)
                    sp.save()
                    i += 1
        if request.is_ajax():
            response_data = get_stack_html(request)
            return JsonResponse(response_data)
    return redirect('players:stack_builder')


@login_required(login_url="/")
def remove(request):
    user = request.user
    if request.method == "POST":
        for p_id, key in request.POST.items():
            if key == "player":
                StackPlayer.objects.get(pk=int(p_id)).delete()
        stacks = Stack.objects.filter(user=user)
        for s in stacks:
            if not s.players.all().exists():
                s.delete()
            else:
                for i, p in enumerate(s.players.all(), start=1):
                    p.order_spot = i
                    p.save()
        if request.is_ajax():
            response_data = get_stack_html(request)
            return JsonResponse(response_data)
    return redirect('players:stack_builder')


@login_required(login_url="/")
def lineups(request):
    lines, pplay = None, None
    p1, p2 = None, None
    if request.method == "POST":
        p1_id = request.POST.get("p1")
        p2_id = request.POST.get("p2")
        p1 = Player.objects.get(id=p1_id)
        p2 = Player.objects.get(id=p2_id)
        salary = p1.salary + p2.salary
        lines = all_lines(50000 - salary, punt=False)
        pplay = all_lines(50000 - salary, punt=True)
    user = request.user
    pitchers = Player.objects.all_starters()
    groups = ExportLineup.objects.group(user)
    saved_lus = tm_cnt(user.pk)
    p_cnt = pitcher_cnt(user.pk)
    h_cnt = hitter_cnt(user.pk)
    total_lus = 0
    for p in p_cnt:
        total_lus += int(p["cnt"])
    total_lus = total_lus * 0.5
    cont_dict = {
        "pitchers": pitchers,
        "lines": lines,
        "pplays": pplay,
        "saved_lus": saved_lus,
        "p_cnt": p_cnt,
        "total_lus": total_lus,
        "h_cnt": h_cnt,
        "groups": groups,
        "p1": p1,
        "p2": p2,
    }
    return render(request, "slate/lineups.html", cont_dict)


@login_required(login_url="/")
def add_lineups(request):
    if request.method == "POST":
        save_lus(request.POST, request.user)
    return redirect("slate:lineups")


@login_required(login_url="/")
def delete_all(request):
    ExportLineup.objects.filter(user=request.user).delete()
    return redirect("slate:lineup_builder")


@login_required(login_url="/")
def update_pro_orders(request):
    update_projected()
    return redirect("players:index")


@login_required(login_url="/")
def lineup_check(request):
    cont_dict = {
        "players": not_in_order_players(request.user.pk)
    }
    return render(request, "slate/lineup_check.html", cont_dict)


@login_required(login_url="/")
def refresh_big_kahuna(request):
    refresh_bkg()
    return redirect("slate:lineups")


@login_required(login_url="/")
def add_punts(request):
    if request.method == "POST":
        user = request.user
        for p_id, key in request.POST.items():
            if key == "player":
                p = Player.objects.get(id=int(p_id))
                if not Punt.objects.filter(user=user, dkid=p.dkid).exists():
                    sp = Punt(user=user, dkid=p.dkid, name_id=p.name_id, position=p.position, salary=p.salary)
                    sp.save()
                else:
                    Punt.objects.filter(user=user, dkid=p.dkid).delete()
        if request.is_ajax():
            response_data = get_stack_html(request)
            return JsonResponse(response_data)
    return redirect('players:stack_builder')


@login_required(login_url="/")
def remove_punts(request):
    if request.method == "POST":
        for p_id, key in request.POST.items():
            if key == "player":
                Punt.objects.get(pk=int(p_id)).delete()
        if request.is_ajax():
            response_data = get_stack_html(request)
            return JsonResponse(response_data)
    return redirect('players:stack_builder')


@login_required(login_url="/")
def delete_bad_lines(request):
    bad_players = not_in_order_players(request.user.pk)
    for p in bad_players:
        player = Player.objects.get(name_id=p["p"])
        pos = player.position
        pos2 = player.position
        if pos == "OF":
            ExportLineup.objects.filter(
                Q(of1=player.name_id) |
                Q(of2=player.name_id) |
                Q(of3=player.name_id)
            ).delete()
        else:
            ExportLineup.objects.filter(**{pos_swap[pos]: player.name_id}).delete()
        if pos2 != "":
            if pos2 == "OF":
                ExportLineup.objects.filter(
                    Q(of1=player.name_id) |
                    Q(of2=player.name_id) |
                    Q(of3=player.name_id)
                ).delete()
            else:
                ExportLineup.objects.filter(**{pos_swap[pos2]: player.name_id}).delete()
    return redirect("slate:lineups")


@login_required(login_url="/")
def update_live_lineups(request):
    manual_live_lu_update()
    return redirect('players:stack_builder')


@login_required(login_url="/")
def team_breakdown(request):
    if request.is_ajax:
        user = request.user
        team_id = request.POST.get("team")
        p_combo, batters, pitchers, lu_type = team_breakdown_data(team_id, user.pk)
        cont_dict = {
            "p_combo": p_combo,
            "batters": batters,
            "pitchers": pitchers,
            "lu_type": lu_type
        }
        html = render_to_string("slate/team_breakdown.html", cont_dict, request=request)
        response_data = {"html": html}
        return JsonResponse(response_data)
    return redirect("slate:lineups")


@login_required(login_url="/")
def lineup_builder(request):
    if request.method == "POST":
        user = request.user
        save_pown = request.POST.get("save", None)
        if not save_pown:
            save_lineups_new_pitchers_first(request.POST, user)
        else:
            line_config = {"proj": {}, "teams": {}, "bats": {}}
            line_config["total"] = request.POST.get("total_lus") if not save_pown else 1
            for p, percent in request.POST.items():
                if p.startswith("team_"):
                    if float(percent) > 0 or save_pown:
                        count = int(int(line_config["total"]) * float(percent))
                        line_config["teams"][p.split("_")[1]] = count if not save_pown else float(percent)
                elif p.startswith("bat_"):
                    if float(percent) > 0 or save_pown:
                        batter = int(p.split("_")[1])
                        count = int(int(line_config["total"]) * float(percent))
                        line_config["bats"][batter] = count if not save_pown else float(percent)
                elif p.startswith("proj_"):
                    if float(percent) > 0 or save_pown:
                        batter = int(p.split("_")[1])
                        pnts = float(percent)
                        print(batter, pnts)
                        line_config["proj"][batter] = pnts
            Player.update_max_pown(line_config["bats"], line_config["teams"], line_config["proj"])
            Team.update_max_pown(line_config["teams"])
    teams = Team.objects.filter(on_slate=True).order_by("-max_stack")
    batters = Player.objects.all_slate_batters()
    pitchers = Player.objects.all_starters()
    user = request.user
    groups = ExportLineup.objects.group(user)
    saved_lus = tm_cnt(user.pk)
    p_cnt = pitcher_cnt(user.pk)
    h_cnt = hitter_cnt(user.pk)
    total_lus = 0
    for p in p_cnt:
        total_lus += int(p["cnt"])
    total_lus = total_lus * 0.5
    combos = PitcherCombo.objects.filter(user=user)
    total_percent = PitcherCombo.objects.total_percentage(user)["sum"] * 100
    total_pitcher = total_pitcher_percent(user.id)
    cont_dict = {
        "teams": teams,
        "pitchers": pitchers,
        "batters": batters,
        "saved_lus": saved_lus,
        "p_cnt": p_cnt,
        "total_lus": total_lus,
        "h_cnt": h_cnt,
        "groups": groups,
        "combos": combos,
        "total_percent": total_percent,
        "total_pitcher": total_pitcher
    }
    return render(request, "slate/slate_builder.html", cont_dict)


@login_required(login_url="/")
def pitcher_combos(request):
    lines, pplay = None, None

slate/templates/slate/lineup_builder.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<div class="container">
    <div class="main" style="margin-top: 20px; float: left; font-size: 1em">
        <div class="row">
            <div class="col-sm-8">
                {% if teams %}
                <form action="{% url 'slate:lineup_builder' %}" method="POST" id="lineup-builder">{% csrf_token %}
                    <div class="row">
                        <div class="col">
                            <div style="padding; 3px">
                                <label for="total_lus">Total Lineups</label>
                                <input type="number" id="total_lus" name="total_lus" value="0">
                            </div>
                            {% for p in pitchers %}
                            <div style="padding; 3px">
                                {{ p }}<input type="number" id="pit_{{ p.pk }}" name="pit_{{ p.pk }}" value="0">
                            </div>
                            {% endfor %}
                        </div>
                        <div class="col">
                            {% for t in teams %}
                            <div style="padding; 3px">
                                {{ b }}<input type="number" id="team_{{ t }}" name="team_{{ t }}" value="0">
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary">Create LUs</button>
                </form>
                {% endif %}
            </div>
        </div>
        <div class="col-sm-4">
        </div>
    </div>
</div>
<!--<script type="text/javascript" charset="utf8">-->
<!--    $(document).ready(function() {-->

<!--        $('#lineup-builder').submit(function(event) {-->
<!--            event.preventDefault();-->
<!--            var team = $(this).attr('data-team')-->
<!--            var url = '{% url 'slate:lineup_builder' %}';-->
<!--            var method = 'POST'-->
<!--            var data = {"team": team}-->
<!--            $.ajax({-->
<!--                url: url,-->
<!--                method: method,-->
<!--                data: data,-->
<!--                success: function(responseData){-->
<!--                    $( "#pstats-modal" ).html(responseData.html);-->
<!--                    $('#bannerformmodal').modal('show');-->
<!--                }, error: function(error){-->
<!--                    console.log(error);-->
<!--                }-->
<!--            })-->
<!--        });-->

<!--    } );-->
<!--</script>-->
{% endlocaltime %}
{% endblock %}

slate/templates/slate/lineup_check.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<body class="body">
<div class="main" style="margin: 20px; font-size: 2em">
    <div style="text-align: center">
        <h1>Not In Start Lineup</h1>
        {% if players %}
        {% for p in players %}
        <p>{{ p.p }} In {{ p.cnt }} Lineups</p>
        {% endfor %}
        {% endif %}
    </div>
</div>
</body>
{% endlocaltime %}
{% endblock %}

slate/templates/slate/lineups.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<body class="body">
<div class="main" style="margin: 20px; float: left; font-size: 2em">
    <form action="{% url 'slate:lineups' %}" method="POST">{% csrf_token %}
        <select name="p1">
            {% if pitchers %}
            {% for p in pitchers %}
            <option value="{{ p.id }}">{{ p }} ${{ p.salary }}</option>
            {% endfor %}
            {% endif %}
        </select>
        <select name="p2">
            {% if pitchers %}
            {% for p in pitchers %}
            <option value="{{ p.id }}">{{ p }} ${{ p.salary }}</option>
            {% endfor %}
            {% endif %}
        </select>
        <button type="submit" class="btn btn-secondary">Fetch Lineups</button>
    </form>
    {% if lines %}
    <form action="{% url 'slate:add_lineups' %}" method="POST">{% csrf_token %}
    {% if p1 and p2 %}
        <input type="hidden" name="p1" value="{{ p1.pk }}">
        <input type="hidden" name="p2" value="{{ p2.pk }}">
        <h1>{{ p1 }}</h1>
        <h1>{{ p2 }}</h1>
    {% endif %}
        <input type="number" name="unique" value="2"/>
    {% for l in lines %}
        <div style="padding; 3px">
            <label for="{{ l.TMCODE }}">{{ l.TMCODE }} => {{ l.lus }}</label>
            <input type="number" id="{{ l.TMCODE }}" name="{{ l.TMCODE }}" value="0">
        </div>
    {% endfor %}
        <button type="submit" class="btn btn-primary">Add LUS</button>
    </form>
    {% endif %}
    {% if pplays %}
    <form action="{% url 'slate:add_lineups' %}" method="POST">{% csrf_token %}
    {% if p1 and p2 %}
        <input type="hidden" name="p1" value="{{ p1.pk }}">
        <input type="hidden" name="p2" value="{{ p2.pk }}">
        <h1>{{ p1 }}</h1>
        <h1>{{ p2 }}</h1>
    {% endif %}
        <input type="number", name="unique" value="2"/>
    {% for l in pplays %}
        <div style="padding; 3px">
            <label for="{{ l.TMCODE }}-punt">{{ l.TMCODE }} => {{ l.lus }}</label>
            <input type="number" id="{{ l.TMCODE }}-punt" name="{{ l.TMCODE }}" value="0">
        </div>
    {% endfor %}
        <input type="checkbox" name="punt" value="punt" hidden checked>
        <button type="submit" class="btn btn-primary">Add LUS</button>
    </form>
    {% endif %}
</div>
{% include 'slate/my_lineups.html' %}
<div class="modal fade bd-example-modal-lg" id="bannerformmodal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" id="pstats-modal">
    </div>
  </div>
</div>
</body>
<script type="text/javascript" charset="utf8">
    $(document).ready(function() {

        $('.team-bd').click(function() {
            var team = $(this).attr('data-team')
            var url = '{% url 'slate:team_breakdown' %}';
            var method = 'POST'
            var data = {"team": team}
            $.ajax({
                url: url,
                method: method,
                data: data,
                success: function(responseData){
                    $( "#pstats-modal" ).html(responseData.html);
                    $('#bannerformmodal').modal('show');
                }, error: function(error){
                    console.log(error);
                }
            })
        });

    } );
</script>
{% endlocaltime %}
{% endblock %}

slate/templates/slate/my_lineups.html
<div class="row">
    <div class="col">
        {% if total_lus %}
        <h3>Total: {{ total_lus }}</h3>
        {% endif %}
        {% if p_cnt %}
        {% for p in p_cnt %}
        <h5>{{ p.p }} {{ p.cnt }}</h5>
        {% endfor %}
        {% endif %}
        {% if saved_lus %}
        <h3>Total team count</h3>
        {% for l in saved_lus %}
        <p><a href="#" data-toggle="modal" class="team-bd"  data-team="{{ l.tm }}">{{ l.tm }} => {{ l.cnt }}</a></p>
        {% endfor %}
        {% endif %}
        {% if groups %}
        <h3>Total Combo Count</h3>
        {% for g in groups %}
        <p><a href="#" data-toggle="modal" class="team-bd"  data-team="{{ g.combo }}">{{ g.combo }} => {{ g.lu_count }}</a></p>
        {% endfor %}
        {% endif %}
        <form action="{% url 'slate:delete_all' %}" method="POST">{% csrf_token %}
            <button type="submit" class="btn btn-primary">Remove Lineups</button>
        </form>
    </div>
    <div class="col">
        {% if h_cnt %}
        {% for h in h_cnt %}
        <p>
            <a href="#" data-toggle="modal" class="team-stats" data-team="{{ h.team }}" data-pitcher="{{ h.opp }}">
                {{ h.p }} {{ h.team }}<br>
                {{ h.pos }} {{ h.pos2 }} {{ h.sal}}
            </a><br>
            Count: {{ h.cnt }} Your POwn: {{ h.mypown }}<br>
            Field Owned: {{ h.pown }} Diff From Field: {{ h.field }}
        </p>
        {% endfor %}
        {% endif %}
    </div>
</div>

slate/templates/slate/pitcher_combos.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<div class="container">
    <div class="main" style="margin: 20px; float: left; font-size: 1.25em">
        <div class="row">
            <div class="col-sm-7">
                <form action="{% url 'slate:pitcher_combos' %}" method="POST">{% csrf_token %}
                    <select name="p1">
                        {% if pitchers %}
                        {% for p in pitchers %}
                        <option value="{{ p.id }}">{{ p }} ${{ p.salary }}</option>
                        {% endfor %}
                        {% endif %}
                    </select>
                    <select name="p2">
                        {% if pitchers %}
                        {% for p in pitchers %}
                        <option value="{{ p.id }}">{{ p }} ${{ p.salary }}</option>
                        {% endfor %}
                        {% endif %}
                    </select>
                    <button type="submit" class="btn btn-secondary">Fetch Lineups</button>
                </form>
                {% if lines %}
                {% for l in lines %}
                <p>{{ l.TMCODE }} => {{ l.lus }}</p>
                {% endfor %}
                {% for l in pplays %}
                <p>{{ l.TMCODE }} => {{ l.lus }}</p>
                {% endfor %}
                <form action="{% url 'slate:pitcher_combos' %}" method="POST">{% csrf_token %}
                    {% if p1 and p2 %}
                    <input type="hidden" name="p1" value="{{ p1.pk }}">
                    <input type="hidden" name="p2" value="{{ p2.pk }}">
                    <h5>{{ p1 }}</h5>
                    <h5>{{ p2 }}</h5>
                    {% endif %}
                    <input type="number" step=".01" class="form-control" id="percent" name="percent" value="0.00" aria-label="Small">
                    <input type="checkbox" name="save" value="save" id="save-check" hidden checked>
                    <button type="submit" class="btn btn-primary">Submit Combo Percentage</button>
                </form>
                {% endif %}
            </div>
            <div class="col-sm-5">
                {% include 'slate/snippets/pcombos.html' %}
            </div>
        </div>

    </div>
</div>
{% endlocaltime %}
{% endblock %}

slate/templates/slate/slate_builder.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
{% load tz %}
{% localtime on %}
<body class="body">
<div class="main">
    <div class="container-fluid" style="margin-top: 20px; font-size: 1.25em">
        <div class="row">
            <div class="col-sm-7">
                {% if teams %}
                <form action="{% url 'slate:lineup_builder' %}" method="POST" id="lineup-builder">{% csrf_token %}
                    <button type="submit" class="btn btn-primary w-100">Create LUs</button>
                    <button type="submit" class="btn btn-primary w-100" id="save-max-owner">Save Max Ownership</button>
                    <input type="checkbox" name="save" value="save" id="save-check" hidden>
                    <div class="row">
                        <div class="col">
                            <div style="padding; 3px">
                                <label for="total_lus">Total Lineups</label>
                                <input type="number" id="total_lus" name="total_lus" value="0" width="5">
                            </div>
                            {% include 'slate/snippets/pcombos.html' %}
                        </div>
                        <div class="col">
                            {% for t in teams %}
                            <div class="input-group input-group-sm mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="lbl{{ t.pk }}">{{ t }}</span>
                                </div>
                                <input type="number" step=".01" class="form-control" id="team_{{ t }}"
                                       name="team_{{ t }}" value="{{ t.max_stack }}" aria-label="Small"
                                       aria-describedby="lbl{{ t.pk }}">
                            </div>
                            {% endfor %}
                        </div>
                        <div class="col">
                            {% for b in batters %}
                            <div class="input-group input-group-sm mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="lbl{{ b.pk }}" style="font-size: 1em">{{ b }} {{ b.salary }}<br>CALC: {{ b.proj_pown }} PROJ: {{b.pown}}</span>
                                </div>
                                <input type="number" step=".01" class="form-control" id="bat_{{ b.pk }}"
                                       name="bat_{{ b.pk }}" value="{{ b.max_pown }}" aria-label="Small"
                                       aria-describedby="lbl{{ b.pk }}">
                                <input type="number" step=".01" class="form-control" id="proj_{{ b.pk }}"
                                       name="proj_{{ b.pk }}" value="{{ b.pts }}" aria-label="Small"
                                       aria-describedby="lbl{{ b.pk }}">
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                </form>
                {% endif %}
            </div>
            <div class="col-sm-5">
                {% include 'slate/my_lineups.html' %}
            </div>
        </div>
    </div>
    <div class="modal fade bd-example-modal-lg" id="bannerformmodal" tabindex="-1" role="dialog"
         aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" style="width:1500px">
            <div class="modal-content" id="pstats-modal" style="width:1250px">
            </div>
        </div>
    </div>
</div>
</body>
<script type="text/javascript" charset="utf8">
    $(document).ready(function() {

        $('#save-max-owner').click(function(event) {
            event.preventDefault();
            $("#save-check").prop("checked", true);
            $('#lineup-builder').submit();
        });

        $('.team-bd').click(function() {
            var team = $(this).attr('data-team')
            var url = '{% url 'slate:team_breakdown' %}';
            var method = 'POST'
            var data = {"team": team}
            $.ajax({
                url: url,
                method: method,
                data: data,
                success: function(responseData){
                    $( "#pstats-modal" ).html(responseData.html);
                    $('#bannerformmodal').modal('show');
                }, error: function(error){
                    console.log(error);
                }
            })
        });

        $('.team-stats').click(function () {
            var team = $(this).attr('data-team');
            var pitcher = $(this).attr('data-pitcher');
            var url = "{% url 'players:pstats' %}";
            var method = 'POST';
            var data = {"team": team, "pitcher": pitcher};
            $.ajax({
                url: url,
                method: method,
                data: data,
                success: function (responseData) {
                    $("#pstats-modal").html(responseData.html);
                    $('#pstats').dataTable({
                        paging: false
                    });
                    $('#indy-pitcher').dataTable({
                        paging: false
                    });
                    $('#bannerformmodal').modal('show');
                }, error: function (error) {
                    console.log(error);
                }
            })
        });
    });

</script>
{% endlocaltime %}
{% endblock %}

slate/templates/slate/team_breakdown.html
<div class="row" style="margin: 20px; font-size: 1.5em">
    <div class="col">
        <h1>Pitcher Combos</h1>
        {% if p_combo %}
        {% for p in p_combo %}
        <p>{{ p.p1 }} - {{ p.p2 }} {{ p.cnt }}</p>
        {% endfor %}
        {% endif %}
        <h1>Totals</h1>
        {% if pitchers %}
        {% for p in pitchers %}
        <p>{{ p.p }} - {{ p.cnt }}</p>
        {% endfor %}
        {% endif %}
        <h1>Lineup Types</h1>
        {% if lu_type %}
        {% for lut in lu_type %}
        <p>{{ lut.type }} - {{ lut.cnt }}</p>
        {% endfor %}
        {% endif %}
    </div>
    <div class="col">
        <h1>Batters</h1>
        {% if batters %}
        {% for p in batters %}
        <p>{{ p.p }} - {{ p.cnt }}</p>
        {% endfor %}
        {% endif %}
    </div>

</div>