account/urls.py
from django.conf.urls import url
from account import views

app_name = 'account'

urlpatterns = [
    url(r'^signup', views.signup, name='signup'),
    url(r'^user_logout', views.user_logout, name='user_logout'),
    url(r'^user_login', views.user_login, name='user_login'),
    url(r'^active_bets', views.active_bets, name='active_bets'),
    url(r'^$', views.account_home, name='account_home'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^history', views.bet_history, name='history'),
    url(r'^update_history', views.update_history, name='update_history'),
]

api/urls.py
from django.urls import path
from .views import ListEventsView, LiveEventsView


urlpatterns = [
    path('events/', ListEventsView.as_view(), name="events-all"),
    path('sports/', LiveEventsView.as_view(), name="live-events"),
]

betslip/urls.py
from django.conf.urls import url
from .views import slip_home, slip_update, parley_update, submit_bet, check_out, cancel_bet


app_name = 'betslip'

urlpatterns = [
    url(r'^$', slip_home, name='home'),
    url(r'^update/$', slip_update, name='update'),
    url(r'^parley_update/$', parley_update, name='parley_update'),
    url(r'^submit_bet/$', submit_bet, name='submit_bet'),
    url(r'^check_out/$', check_out, name='check_out'),
    url(r'^cancel_bet/$', cancel_bet, name='cancel_bet'),
]

players/urls.py
from django.urls import path
from . import views

app_name = 'players'

urlpatterns = [
    path('upload_players', views.upload_player, name='upload_players'),
    path('available_lineups', views.available_lineups, name='available_lineups'),
    path('stats', views.stats, name='stats'),
    path('starters_order', views.starters_order, name='starters_order'),
    path('stack_builder', views.stack_builder, name='stack_builder'),
    path('', views.index, name='index'),
    path('pitching', views.pitching_stats, name='pitching'),
    path('stacks', views.stacks_stats, name='stacks'),
    path('pstats', views.team_stats, name='pstats'),
    path('player_bats', views.player_bats, name='player_bats'),
    path('pull_projections', views.pull_projections, name='pull_projections'),
    path('stacks_call', views.stacks_call, name='stacks_call'),
    path('pown', views.player_pown, name='pown'),
    path('add_starter', views.add_starter, name='add_starter'),
]

slate/urls.py
from django.urls import path
from . import views

app_name = 'slate'

urlpatterns = [
    path("stack_add", views.stack_add, name="stack_add"),
    path("remove", views.remove, name="remove"),
    path("lineups", views.lineups, name="lineups"),
    path("add_lineups", views.add_lineups, name="add_lineups"),
    path("delete_all", views.delete_all, name="delete_all"),
    path("update_orders", views.update_pro_orders, name="update_pro_orders"),
    path("lineup_check", views.lineup_check, name="lineup_check"),
    path("refresh_lus", views.refresh_big_kahuna, name="refresh_lus"),
    path("add_punts", views.add_punts, name="add_punts"),
    path("remove_punts", views.remove_punts, name="remove_punts"),
    path("delete_bad_lines", views.delete_bad_lines, name="delete_bad_lines"),
    path("update_line_lineups", views.update_live_lineups, name="update_live_lineups"),
    path("team_breakdown", views.team_breakdown, name="team_breakdown"),
    path("lineup_builder", views.lineup_builder, name="lineup_builder"),
    path("pitcher_combos", views.pitcher_combos, name="pitcher_combos"),
    path("delete_pcombo", views.delete_pcombo, name="delete_pcombo"),
]

thebook/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from django.conf.urls import include
from sportsbook import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^sportsbook/', include('sportsbook.urls', namespace='sportsbook')),
    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^betslip/', include('betslip.urls', namespace='betslip')),
    path('api/', include('api.urls')),
    path("players/", include('players.urls', namespace='players')),
    path("slate/", include('slate.urls', namespace='slate')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en"> <!-- need to remove -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" type="image/png" href='{% static "images/icon.png" %}'>
    <link rel="apple-touch-icon" href="{% static 'images/icon.png' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    {% include 'base/css.html' %}

    <title>The Book</title>

</head>
<body class="body">

<!-- Nav bar -->
<nav class="navbar  fixed-top navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">The Book BKG</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'sportsbook:home' %}" style="font-size:2em">Home<span class="sr-only">(current)</span></a>
            </li>
            {% if sports %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false" style="font-size:2em">
                    Sports Book
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for s in sports %}
                    <a href="/sportsbook/{{ s.lower_sport }}" class="w-dropdown-link">{{ s.sport }}</a>
                    <div class="dropdown-divider"></div>
                    {% endfor %}
                </div>
            </li>
            {% endif %}
            {% if request.user.is_staff %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false" style="font-size:2em">
                    Fantasy LU Builder
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a href="{% url 'players:upload_players' %}" class="w-dropdown-link">Upload DK Slate</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'players:stats' %}" class="w-dropdown-link">Add Player Stats</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'players:stack_builder' %}" class="w-dropdown-link">Build Stacks</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'slate:pitcher_combos' %}" class="w-dropdown-link">Build Pitcher Combos</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'slate:lineup_builder' %}" class="w-dropdown-link">Create Lineups</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'slate:lineup_check' %}" class="w-dropdown-link">Line Checker</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false" style="font-size:2em">
                    Player Stats
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a href="{% url 'players:pitching' %}" class="w-dropdown-link">Pitching</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'players:stacks' %}" class="w-dropdown-link">Stacks</a>
                </div>
            </li>
            {% endif %}
        </ul>


        {% if user.is_authenticated %}
        <div class="dropdown dropleft">
            <button class="btn account-btn btn-sm dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="font-size:1.5em">
                {{ user.username }} (${{ user.account.balance }})
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'account:account_home' %}">Account Home</a>
                <a class="dropdown-item" href="{% url 'account:active_bets' %}">Placed Bets</a>
                <a class="dropdown-item" href="{% url 'account:history' %}">Bet History</a>
                <a class="dropdown-item" href="{% url 'account:user_logout' %}">Logout</a>
            </div>
        </div>
        {{% else %}
        <a class="btn account-btn btn-sm" type="submit" href="/">Login</a>
        {% endif %}
    </div>
</nav>

{% block body_block %}



{% endblock %}
<!-- Footer -->

{% include 'base/js.html' %}

<script>

</script>


</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block body_block %}
<body class="login-body">
  <div class="w-container">
    <div class="w-form">
      <form id="email-form" action="{% url 'sportsbook:base' %}" method="POST" class="login-form">
          {% csrf_token %}
        <div class="login-image-section"><img src='{% static "images/icon.png" %}' width="100" alt="" class="login-image"></div>
        <h1 class="login-header">Sign In</h1>
        <input type="text" class="login-inputs w-input" maxlength="256" name="username" data-name="user" placeholder="Username" id="user">
        <input type="password" class="login-inputs w-input" maxlength="256" name="password" data-name="password" placeholder="Password" id="password" required="">
        <input type="submit" value="Sign In" data-wait="Please wait..." class="login-submit w-button">
    </form>
    </div>
  </div>
</body>
{% endblock %}